---

- hosts: all
  become: yes
  tasks:
    - name: Install apache package
      package:
        name:
          - "{{ apache_package }}"
        state: latest
        update_cache: yes

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    - name: Allow HTTP and HTTPS permanently and immediately
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - http
        - https
      notify: Reload firewall

- hosts: group1
  become: yes
  tasks:
    - name: Ensure tmux is installed
      package:
        name: tmux
        state: present
