---

- hosts: all
  become: yes
  tasks:
    - name: Install apache package
      tags: apache
      package:
        name:
          - "{{ apache_package }}"
        state: latest
        update_cache: yes

    - name: Start and enable httpd service
      tags: apache
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    - name: Allow HTTP and HTTPS permanently and immediately
      tags: apache
      ansible.posix.firewalld:
        service: "{{ item }}"
        permanent: true
        immediate: true
        state: enabled
      loop:
        - http
        - https
      notify: Reload firewall

    - name: Copy default html file for site
      tags: apache
      copy:
        src: default_site.html
        dest: /var/www/html/index.html
        owner: root
        group: root
        mode: 0644

- hosts: group1
  become: yes
  tasks:
    - name: Ensure tmux is installed
      tags: tmux
      package:
        name: tmux
        state: present
