---
- name: Install and start Apache on RHEL 10
  hosts: all
  become: yes
  tasks:
    - name: Install httpd package
      ansible.builtin.dnf:
        name: httpd
        state: latest
        update_cache: yes
      when: ansible_distribution == "Redhat"

    - name: Start and enable httpd service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes
      when: ansible_distribution == "RedHat"

    - name: Enable http service in firewalld
      ansible.posix.firewalld:
        service: http
        state: enabled
        permanent: true
        immediate: true
      when: ansible_distribution == "Redhat"
