- name: Install httpd package
  tags: apache
  dnf:
    name:
      - "{{ apache_package_name }}"
    state: latest

- name: Start and enable httpd service
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: Allow HTTP and HTTPS permanently and immediately
  tags: apache
  ansible.posix.firewalld:
    service: "{{ item }}"
    permanent: true
    immediate: true
    state: enabled
  loop:
    - http
    - https

- name: change e-mail address for admin
  tags: apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin john.kim@pacxa.com
  when: ansible_distribution == "RedHat"
  register: varstate
        
- name: restart httpd
  tags: apache
  service:
    name: "{{ apache_service }}"
    state: restarted
  when: varstate.changed
