- name: Install httpd package
  tags: apache
  dnf:
    name:
      - httpd
    state: latest

- name: Start and enable httpd service
  tags: apache
  service:
    name: httpd
    state: started
    enabled: yes

- name: Enable http service in firewalld
  tags: apache
  ansible.posix.firewalld:
    service: http
    state: enabled
    permanent: true
    immediate: true

- name: change e-mail address for admin
  tags: apache
  lineinfile:
    path: /etc/httpd/conf/httpd.conf
    regexp: '^ServerAdmin'
    line: ServerAdmin john.kim@pacxa.com
  when: ansible_distribution == "RedHat"
  register: varstate
        
- name: restart httpd
  tags: apache
  service:
    name: httpd
    state: restarted
  when: varstate.changed
